FROM node:16-alpine3.15

WORKDIR /app
RUN chown -R node:node /app
USER node

ENV NODE_ENV production

COPY --chown=node:node package.json package-lock.json ./

# install dev dependencies too
RUN npm ci

COPY --chown=node:node . .
RUN set -x && npm run build

EXPOSE 3000

CMD [ "node", "dist/main.js" ]